// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models;

public partial class Category
{
    public int CategoryId { get; set; }

    public string CategoryName { get; set; }

    public int? CategoryParentId { get; set; }

    public string CategoryImage { get; set; }

    public string CategoryDesc { get; set; }

}