// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models;

public partial class OrderDet
{
    public int RecId { get; set; }

    public int OrderId { get; set; }

    public int ProductId { get; set; }

    public decimal? Discount { get; set; }

    public decimal Price { get; set; }

    public int? ProductQuantity { get; set; }

    public string? ProductColor { get; set; }

    public string? ProductSize { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }
}