// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Models;

public partial class Product
{
    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public string ProductDesc { get; set; }

    public string ProductImages { get; set; }

    public string ProductMainImage { get; set; }

    public decimal ProductPrice { get; set; }

    public decimal? Productdiscount { get; set; }

    public int ProductStockQuantity { get; set; }

    public string ProductSizes { get; set; }

    public string ProductColours { get; set; }

    [Range(0,5)]
    public decimal? ProductRating { get; set; }

    [ForeignKey("Category")]
    public int CategoryId { get; set; }
    public Category Category { get; set; }

}