// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;

namespace Models;

public partial class ShoppingCart
{
    [Key]
    public int ShoppingCartId { get; set; }

    [ForeignKey("Product")]
    public int ProductId { get; set; }
    public Product Product { get; set; }

    [ForeignKey("ApplicationUser")]
    public int UserId { get; set; }
    public ApplicationUser ApplicationUser { get; set; }

    
    public int? ProductQuantity { get; set; }

    public string? ProductColor { get; set; }

    public string? ProductSize { get; set; }


}